name: Build and Release to PyPI

on:
  push:
    branches:
      - main
    #tags:
    #  - "v*"
  workflow_dispatch:

jobs:
  build-release:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install base build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest cibuildwheel pybind11 scikit-build-core

      - name: Run tests (before build)
        run: |
          pip install .[test]
          pytest tests/

      - name: Build manylinux cibuildwheel
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_SKIP: "pp* *-musllinux*"
          CIBW_BUILD: "cp310-* cp311-* cp312-*"
          CIBW_BEFORE_BUILD: "pip install pybind11 scikit-build-core"
          CIBW_BUILD_VERBOSITY: "2"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
