name: Build and Release to PyPI

on:
  push:
    #branches:
    #  - main
    tags:
      - aephisgraph-*
jobs:
  build-release:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      attestations: write
      contents: read

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.12"

      - name: Build wheels
        run: |
          git clean -fxd
          pip install -U build twine wheel
          python -m build --sdist --wheel

      - name: Verify the distribution
        run: twine check --strict dist/*

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
