name: Build and Release to PyPI

on:
  push:
    branches:
      - main
    #tags:
    #  - "v*"
  workflow_dispatch:

jobs:
  build-release:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
          pip install build pytest cibuildwheel

      - name: Run Tests
        run: |
          pytest tests

      - name: Build manylinux cibuildwheel
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_SKIP: pp* cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*  # Keep only cp312
          CIBW_PLATFORM: linux

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
