name: Build and Release to PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-release:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install libomp on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install libomp
          echo "OPENMP_PATH=$(brew --prefix libomp)" >> $GITHUB_ENV
          echo "CMAKE_CXX_FLAGS=-Xpreprocessor -fopenmp" >> $GITHUB_ENV
          echo "CMAKE_EXE_LINKER_FLAGS=-L$OPENMP_PATH/lib -lomp" >> $GITHUB_ENV

      - name: Install base build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel build pytest pybind11 scikit-build-core

      - name: Run tests (before build)
        run: |
          pip install .[test]
          pytest tests/

      - name: Build wheels with cibuildwheel
        env:
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BEFORE_BUILD: pip install pybind11
          CIBW_ENVIRONMENT: >
            CMAKE_BUILD_PARALLEL_LEVEL=4
            SKBUILD_CMAKE_ARGS=-DCMAKE_CXX_FLAGS="-Wno-deprecated-declarations -march=native"
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            export CIBW_ENVIRONMENT="$CIBW_ENVIRONMENT -Xpreprocessor -fopenmp -lomp"
          fi
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
