name: Build and Release to PyPI

on:
  push:
    branches:
      - main
    #tags:
    #  - "v*"

jobs:
  build-release:
    name: Build & Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest

      - name: Run Tests
        run: |
          pip install .[test]
          pytest

      - name: Install cibuildwheel
        run: |
          pip install cibuildwheel

      - name: Build manylinux wheel
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_SKIP: pp* cp36-* cp37-* cp38-*  # Skip unsupported interpreters
          CIBW_BUILD: cp312-manylinux_x86_64
          CIBW_PLATFORM: linux

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
