name: Build and Release to PyPI

on:
  push:
    branches:
      - main
    #tags:
    #  - "v*"
  workflow_dispatch:

jobs:
  build-release:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Set up Python
        uses: actions/setup-python@v5
      
      - name: Install libomp (macOS only)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install libomp
          echo "CMAKE_CXX_FLAGS=-Xpreprocessor -fopenmp -lomp" >> $GITHUB_ENV
          echo "CMAKE_EXE_LINKER_FLAGS=-lomp" >> $GITHUB_ENV
      
      - name: Install base build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest cibuildwheel pybind11 scikit-build-core

      - name: Run tests (before build)
        run: |
          pip install .[test]
          pytest tests/

      - name: Build manylinux cibuildwheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Publish to PyPI
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
